### ISSUE TITLE
Controlled vocabulary for creator affiliations

### ISSUE THREAD

**Issue by haarli** [MPDL/dataverse#1]
GRID data for creator affiliation metadata
https://grid.ac/

Update 19.06.21:
As GRID will be discontinued end of 2021, we will use ROR data instead:
https://ror.org/blog/2021-07-12-ror-grid-the-way-forward/

When entering an affiliation while creating/editing a dataset, an autosuggest field with affilitions from the ROR database must be displayed. When choosing an item form the list, the affiliation field and the ROR identifier field is automatically filled with the corresponding valued. The fields are then locked to hinder the user adding unmatching values (affiliation title - ROR id). They can be unlocked with a button, which also deletes the value from both fields.
It is also possible to add an affiliation title which is not part of the ROR database, just by entering it and not choosing from the autosuggest list.

Edit 15.10.2021:
If possible, Max Planck Society related institutes should be boosted, meaning they should appear first in the list

**Comment by haarli** [comment]
As GRID will be discontinued end of 2021, we will use ROR data instead: 
https://ror.org/blog/2021-07-12-ror-grid-the-way-forward/

**Comment by hofmannc** [comment]
Testserver: prod-edmond2.mpdl.mpg.de
Browser: ff
Version: 08.02.2022
User: Dataverse Admin

Actions: 
create data set -> enter organization -> ROR database displayed -> ok

When choosing an item form the list, the affiliation field and the ROR identifier field is automatically filled with the corresponding valued. ->ok

The fields are then locked to hinder the user adding unmatching values (affiliation title - ROR id). They can be unlocked with a button, which also deletes the value from both fields. ->ok


It is also possible to add an affiliation title which is not part of the ROR database, just by entering it and not choosing from the autosuggest list. ->ok


Observation: all requirements implemented -> ok
