### ISSUE TITLE
Hide "Host Dataverse" and other dataverse-specific elements

### ISSUE THREAD

**Issue by haarli** [MPDL/dataverse#10]
When creating a new Dataset, the user can choose the Dataverse:
![grafik](https://user-images.githubusercontent.com/5524896/130936727-874c3ca7-e8e3-4797-b366-0f6dcd75085c.png)

This section should be hidden, as we intend to have only one dataverse object in the system, and is therefore confusing for the user.

Additionally, the corresponding section should be hidden/removed when editing a dataset.

When searching, the facet "Dataverse" shouldn't be visible, too:
![grafik](https://user-images.githubusercontent.com/5524896/133747005-21230d20-08e7-40ff-9d6a-106a83cf63ee.png)

**Comment by helkv** [comment]
Testserver: prod-edmond2.mpdl.mpg.de
Browser: ff
Version: 14.02.2022
User: User

Actions - Hidden Host Dataverse:
- Create Dataset: Add Data -> New Dataset -> Section and Fields for changing Host Dataverse are not visible :heavy_check_mark: 
- Edit Dataset: Open Dataset -> Edit Dataset -> Metadata -> Section and Fields for changing Host Dataverse are not visible :heavy_check_mark: 

Actions - Hidden Facet Dataverse:
- Open start page -> Facet Dataverse is not visible :heavy_check_mark: 

Observation:
All requirements implemented :heavy_check_mark:
