### ISSUE TITLE
Only allow publishing of datasets with at least one file

### ISSUE THREAD

**Issue by haarli** [MPDL/dataverse#11]
Publishing a dataset should only be allowed when at least one file exists

**Comment by helkv** [comment]
Testserver: prod-edmond2.mpdl.mpg.de
Browser: ff
Version: 14.02.2022
User: User

Actions:
Create Dataset (without a file) -> Publish Dataset -> Dataset can not be published + Error message: _Error – At least one file is required to publish a dataset. If you believe this is an error, please contact Edmond Support for assistance._ :heavy_check_mark: 

Actions (API):
Create Dataset (without a file) -> Publish Dataset via API Call -> 403 - Error - _At least one file is required to publish a dataset._ :heavy_check_mark: 

Observation:
All requirements implemented :heavy_check_mark:

**Comment by helkv** [comment]
Removed this MPDL specific change (https://github.com/MPDL/dataverse/commit/a4d6e7e52ebfcbd6998f502e1edabf6a623dec34) to use the IQSS/dataverse feature "Prevent Publishing of Datasets Without Files", see https://github.com/MPDL/dataverse/issues/82
