### ISSUE TITLE
Improvement of display of authors in dataset metadata overview

### ISSUE THREAD

**Issue by haarli** [MPDL/dataverse#14]
The display of the authors is currently quite confusing as all ROR-Links and ORCID-Links are visible. 
A more structured view with ROR and ORCID icons instead of full http links would be desirable, like this suggestion:

![grafik](https://user-images.githubusercontent.com/5524896/139064934-9cbc64b2-8884-4827-924f-cf5832c332c8.png)

**Comment by helkv** [comment]
Testserver: prod-edmond2.mpdl.mpg.de
Browser: ff
Version: 14.02.2022
User: User

Actions:
Open Dataset -> Open Metadata Tab -> ORCID + ROR icons are visible and clickable (if ORCID/ROR exist) :heavy_check_mark: 

Note:
Data are not (syntactical) validated. ORCID + ROR icons are visible, although the entered Data may not be valid ORCID/ROR addresses -> Correct functionality :question: 

Observation:
All requirements implemented :heavy_check_mark:
