### ISSUE TITLE
Feature Request/Idea:Customise legal documents for Dataverse

### ISSUE THREAD

**Issue by yvgrossmann** [MPDL/dataverse#15]
see different documents [seafile://openfile?repo_id=c0d0d59f-ef1e-4208-9dee-5f584488508d&path=/Product_Owner/Rechtsdokumente_Edmond/](seafile://openfile?repo_id=c0d0d59f-ef1e-4208-9dee-5f584488508d&path=/Product_Owner/Rechtsdokumente_Edmond/)

**Comment by vilarodr** [comment]
[Issue code is on branch <strong>mpdl/15-customise-legal-documents</strong>](https://github.com/MPDL/dataverse/tree/mpdl/15-customise-legal-documents)

**Comment by vilarodr** [comment]
The new Legal Documents are stored on the branding resources folder. To link them, only the Privacy Policy link could be created using the from Dataverse provided definition for the Setting Table on the database. For the other links, it was necessary to insert new custom definitions in the Setting Table and add a few lines of code to the footer of Dataverse on  webapp. It was also necessary to adapt the copyright message and add new ones to the properties bundle. Terms of Use for a dataverse is  direct settled using the Setting Table.
