### ISSUE TITLE
Explore Edmond by "Randomisation generator"

### ISSUE THREAD

**Issue by hofmannc** [MPDL/dataverse#21]
Testserver: https://prod-edmond2.mpdl.mpg.de/
Browser: Chrome / Firefox

Goal of the test: Get inspiration for small test tasks - find unusual ways of system usage -> are they performable?

Please go through Edmond using the randomization generator:

[randomization generator.xlsx](https://github.com/MPDL/dataverse/files/8021685/randomization.generator.xlsx)

Actions:
Please  use the two given columns as "testcase generator":
Identify a "Substantiv-Verb" pair and try to find some testideas for the given elements
-> e.g. "subcollection - delete"
-> ask yourself e.g.:
    How could I perform this action in the system? (Because sometimes the combination does not necessarily make sense)
    Are there several areas in the system where I could perform this test?
    Which elements could I include for the tests? (e.g. sometimes it makes sense to vary data formats/types etc)

It is not necessary to cover all randomized pairs or the whole system - the focus is to get ideas to perform a detailed check of certain parts of Edmond: either you run through the list quickly or you stick with only a few Test cases, because it led you to interesting actions -> the main goal is to find interesting test questions :-)

Please enter comments in the given Excel table and upload in this ticket again.

**Comment by HoMPDL** [comment]
[Ticket für EDMOND.docx](https://github.com/MPDL/dataverse/files/8078466/Ticket.fur.EDMOND.docx)

**Comment by HoMPDL** [comment]
[Kopie von randomization.generator.xlsx](https://github.com/MPDL/dataverse/files/8078470/Kopie.von.randomization.generator.xlsx)
