### ISSUE TITLE
Batch upload of +15 items freezes during upload process

### ISSUE THREAD

**Issue by hofmannc** [MPDL/dataverse#22]
Testserver: prod-edmond2.mpdl.mpg.de
Browser: ff
Version: 08.02.2022
User: Dataverse Admin

Actions:
1. open data file -> "Upload files" -> "select files to add" -> select 15- 10 files -> "Save Changes" -> files added to "Files" -> ok

2. open data file -> "Upload files" -> "select files to add" -> select 17 files ->

Observation: -> view freezes 

![grafik](https://user-images.githubusercontent.com/14921701/153021650-96623b6e-4c75-4cbe-b6b0-81dbb453adf7.png)

and items are not uploaded

Expected result: Files are added to data set successfully

**Comment by haarli** [comment]
Pending Pull Request and issue:
https://github.com/IQSS/dataverse/issues/8408

**Comment by hofmannc** [comment]
Testserver: prod-edmond2.mpdl.mpg.de
Browser: ff
Version: 14.02.2022
User: Admin

Actions:
open data file -> "Upload files" -> "select files to add" -> select 17 files ->

Observation: In my experience, this issue is not sufficently fixed: upload process still freezes every 3-4 th intent.
