### ISSUE TITLE
Decoding problems in language vocabulary

### ISSUE THREAD

**Issue by hofmannc** [MPDL/dataverse#30]
Server: prod-edmond2
Testdate: 14.02.2022
Browser: ff
Version: Dataverse v. 5.8
User: Admin
Action: edit metadata of data set -> "select language:

![grafik](https://user-images.githubusercontent.com/14921701/154043978-3f91fa49-3b5c-465d-9838-ee8d04244da0.png)

Result: Decoding problems in some list items

**Comment by helkv** [comment]
Wrong encoded languages values must have been imported to the server during configuration of the metadata/controlledvocabulary. The cause of the wrong encoding is unknown. 

The wrong encoded language values are duplicates of already existing correct encoded language values.

Fix: Removed the wrong encoded language values (from DB). 
=> List of languages (controlledvocabulary) should now be correct & without wrong encoded values.

**Comment by helkv** [comment]
Updating the Metadata/Controlledvocabulary via API call **api/admin/datasetfield/load** (sending the local citation.tsv configuration), results in the observed incorrect encoded languages in the vocabulary.

TODO: Discover why the languages are wrong encoded.

**Comment by helkv** [comment]
For similar Problems see: https://github.com/IQSS/dataverse/issues/5234, https://github.com/IQSS/dataverse/issues/6675 and https://github.com/IQSS/dataverse/issues/6717

**Solution**: Adding `<jvm-options>-Dfile.encoding=UTF8</jvm-options>` to Payaras _domain.xml_ fixes the Problem (as described here: https://github.com/IQSS/dataverse/issues/5234#issuecomment-434276254).

**Comment by helkv** [comment]
Testserver: qa-edmond2.mpdl.mpg.de
Browser: ff
Version: v5.12.1-mpdl-1 (https://github.com/MPDL/dataverse/commit/3dce49cda89399e4bcdb173e40aa6e553c1db1eb)
User: Admin
Result: OK

No more encoding issues in the controlled vocabulary when sending the local citation.tsv configuration via API call **api/admin/datasetfield/load**
