### ISSUE TITLE
Feature Request/Idea: Direct Download Link for File Items not only for CC0

### ISSUE THREAD

**Issue by yvgrossmann** [MPDL/dataverse#32]
The link for the direct download of the file item level is only visible in the metadata when the dataset has a CC0 license. For all other license, the direct link is only accessible via the download button and the acceptance of the license terms of use.
Another way to manage this would present the direct download path for every file item, independent of the license status.

**Comment by haarli** [comment]
After further investigation, it's not the CC0 license which prevents the display of the link, but the terms of use field. During migration, this field was filled with information which lead to the effect.

The terms of use field is now deleted for migrated items (if they have a license set). Now, nearly all datasets should display the link, except for the ones which really have special terms of use.
