### ISSUE TITLE
Dataset Lock during Publication due to missing File

### ISSUE THREAD

**Issue by helkv** [MPDL/dataverse#33]
Sometimes during the Dataset publication process the Dataset gets locked due to issues reading a file (which does not exist in the DB). The Dataset stays locked until it gets manually unlocked (via locks API).

Relevant Dataverse Log:
`Finalizing publication of the dataset doi: ...`
`Failed to open datafile id ... for reading`
`CommandException caught when executing the asynchronous portion of the Dataset Publication Command.`

The issue was observed two times with migrated Datasets, but could not be reproduced on the test system.
Since the issued files did not exit in the DB, the error could be connected to caching problems, for example: A deleted file is still cached, which results in the described error during publication.

**Comment by haarli** [comment]
Caching is deactivated for now.
