### ISSUE TITLE
Add hint that edmond support is provided in english and german

### ISSUE THREAD

**Issue by haarli** [MPDL/dataverse#35]
Add a hint that support is provided in english and german language when clicking "Support" in the main menu or "Contact" on the start page.

**Comment by hofmannc** [comment]
Testserver: qa-edmond2.mpdl.mpg.de
Browser: ff
Version: 5.10.1
User: admin

Actions: -> start page -> "contact" 

Observation: -> (English/German) is displayed.

"Support" in main menue not displayed

Expected result: ok for "contact"
tp be discuddes for "support"

**Comment by helkv** [comment]
The Support button is visible again (due to an update of the css https://github.com/MPDL/dataverse/commit/d037b5b0c82dff3d6ee76f13079639a2e8802197).

'(English/German)' is also displayed in the Contact-Dialog via the Support button.
