### ISSUE TITLE
Add @type Person to JSON-LD export of authors

### ISSUE THREAD

**Issue by haarli** [MPDL/dataverse#36]
Currently, Google Dataset Search does not display author informartion, as it requires the `@type` Person  for each author. Currently, there's no type exported, see discussion here: 
See also https://github.com/IQSS/dataverse/issues/5029

For edmond, the `@type` Person should be added, as we only have persons as authors

**Comment by helkv** [comment]
Testserver: qa-edmond2.mpdl.mpg.de
Browser: ff
Version: 5.10.1-mpdl-1
User: -
Observation: JSON-LD contains "@type": "Person" for creator and author
Result: OK
