### ISSUE TITLE
Dataverse v5.11 Merge

### ISSUE THREAD

**Issue by haarli** [MPDL/dataverse#39]
Ticket for all adaptions & fixes related to merging new Dataverse Version v5.11 and current mpdl-develop Version.

For the Release Notes of Dataverse v5.11, see: https://github.com/IQSS/dataverse/releases/tag/v5.11

**Comment by helkv** [comment]
Testserver: qa-edmond2.mpdl.mpg.de
Browser: ff
Version: v5.11-mpdl-1 (https://github.com/MPDL/dataverse/commit/07188f34c4aad04f6de0ad7f11c795e7c9d4f5c4)
User: Admin
Result: OK

**Comment by haarli** [comment]
Postponed, as in the meanwhile a new version v5.11.1 is out. v5.11 is not recommended anymore.
https://github.com/IQSS/dataverse/releases/tag/v5.11
