### ISSUE TITLE
Add a mapping for the different organization names

### ISSUE THREAD

**Issue by helkv** [MPDL/dataverse#41]
The Author Organization Facet lists different names for the same Max Planck Institutes. (For example "MPI for Chemical Ecology" and "Max Planck Institute for Chemical Ecology" are two spellings of the same institute).

Add a mapping to the Solr index, so that each Max Planck Institute with different spelling is mapped to the official name of the Institute (ideally the ROR name). This way the submitted organization name is not changed, but organizations with different names are listed under one name in the Author Organization Facet.

Use the following mappings for the Institute names:
```
Max Planck Institut für Chemie -> Max Planck Institute for Chemistry
Max-Planck-Institut für Kolloid- und Grenzflächenforschung -> Max Planck Institute of Colloids and Interfaces
MPI for -> Max Planck Institute for
MPI of -> Max Planck Institute of
```

**Comment by helkv** [comment]
Implementation, see commit: ccffebf46839c82371d92fd6a3bf9cf2d69db6c1

**Comment by wilhelmfrank** [comment]
changes to schema.xml and the appropriate charFilterMapping are here:
https://github.com/MPDL/dataverse/commit/ccffebf46839c82371d92fd6a3bf9cf2d69db6c1
After copying the files to Solr, a complete reindex is required:
1. <dataverse_instance>/api/admin/index/clear
2. check if Solr index data is empty (<solr-home>/server/solr/collection1/data/index)
3. remove remaining files and restart Solr.
4. <dataverse_instance>/api/admin/index

**Comment by helkv** [comment]
Testserver: qa-edmond2.mpdl.mpg.de
Browser: ff
Version: v5.11-mpdl-1 (07188f3)
User: User
Result: OK

**Comment by wilhelmfrank** [comment]
updated filter_mapping.txt according to https://jira.mpdl.mpg.de/browse/FDM-135

**Comment by hofmannc** [comment]
Testserver: qa-edmond2.mpdl.mpg.de
Browser: ff
Version: v5.12.1-mpdl-1
User: Admin
Result: 
<html><body>


Max Planck institute for the science of human history, Jena, Germany | Max Planck Institute for the Science of Human History
-- | --
MPI für Evolutionsbiologie | Max Planck Institute for Evolutionary Biology
MPI für Eisenforschung GmbH | Max-Planck-Institut für Eisenforschung GmbH
Department of Evolutionary Neuroethology, Prof. B. S. Hansson, Max Planck Institute for Chemical Ecology, Max Planck Society | Max Planck Institute for Chemical Ecology
Max-Planck Institute of colloids and interfaces | Max Planck Institute of Colloids and Interfaces
Max-Planck-Institut für empirische Ästhetik | Max Planck Institute for Empirical Aesthetics
MPDL | Max Planck Digital Library
max planck institute for empirical aesthetics | Max Planck Institute for Empirical Aesthetics
Atmospheric Chemistry, Max Planck Institute for Chemistry, Max Planck Society | Max Planck Institute for Chemistry
Andrew Mackenzie, Physics of Quantum Materials, Max Planck Institute for Chemical Physics of Solids, Max Planck Society | Max Planck Institute for Chemical Physics of Solids
MPI für Kohlenforschung | Max-Planck-Institut für Kohlenforschung


</body>
</html>

**Comment by hofmannc** [comment]
Testserver: qa-edmond2.mpdl.mpg.de
Browser: ff
Version: v5.12.1-mpdl-1
User: Admin
Testcase: create data set -> enter author organization of left column-> save -> author organization of right column is displayed in facet -> dataset is included to right column
Result: nok, MPDL -> Max Planck Digital Library is not included to mapping.
All other mapping pairs are ok.

**Comment by haarli** [comment]
Can be closed, as discussed
