### ISSUE TITLE
Metadata field keyword shows inconsistent behaviour during upload process (+200 items)

### ISSUE THREAD

**Issue by hofmannc** [MPDL/dataverse#42]
Server: qa-edmond2
Testdate: 02.08.2022
Browser: ff
Version: Dataverse v. 5.11
User: Admin
Action: Start page -> "Add data" -> "New dataset" -> fill out mandatory fields -> "Select files to add" -> select +200 items ->

Observation: During the upload process, the entry field "keyword" is growing continuously.

Action: enter keyword "a" and "b" as displayed:
![image](https://user-images.githubusercontent.com/14921701/182359263-37de8ae5-795c-408d-8ba4-7ddb9b919572.png)

Observation:
With entering keyword "b", Keyword "a" is inserted in each following line of the entry field (after a while replaced by keyword "b")

Action: "save data set" ->

Observation:
1. -> Landing page of data set and section "metadata" -> only keyword "b" displayed
![image](https://user-images.githubusercontent.com/14921701/182359951-35005470-310f-44e7-a578-5ce0574aa5ad.png)

Expected result: Keyword "a" and "b" displayed

2. -> "edit dataset" -> "metadata" -> Keyword "b" displayed twice
![image](https://user-images.githubusercontent.com/14921701/182360265-c217e627-830a-4574-a2cc-0c0da30b6b79.png)

Expected result: Keyword "a" and "b" displayed

**Comment by helkv** [comment]
Testserver: qa-edmond2.mpdl.mpg.de
Browser: ff
Version: v5.11-mpdl-1.1 (https://github.com/MPDL/dataverse/commit/11541b695dc08268da83cfefe5df0a61862bf5d1)
User: User
Result: OK

**Comment by hofmannc** [comment]
Testserver: qa-edmond2.mpdl.mpg.de
Browser: ff
Version: v5.12.1-mpdl-1
User: Admin
Result: OK
