### ISSUE TITLE
FASTA file detection

### ISSUE THREAD

**Issue by haarli** [MPDL/dataverse#46]
Currently, FASTA files with endings .fasta are detected as an unknown file type. Thus, no preview as text is possible.

Dataverse provides a properties file named MimeTypeDetectionByFileExtenstion.properties, which allows to add mappings from certain file extensions to mime types. 
For FASTA files, the following entries might make sense:
```properties
fasta=application/x-fasta
fa=application/x-fasta
fna=application/x-fasta
ffn=application/x-fasta
faa=application/x-fasta
frn=application/x-fasta
```

**Comment by helkv** [comment]
Testserver: qa-edmond2.mpdl.mpg.de
Browser: ff
Version: v5.12.1-mpdl-1 (3dce49cd)
User: User
Result: OK
