### ISSUE TITLE
v5.12 Merge

### ISSUE THREAD

**Issue by haarli** [MPDL/dataverse#47]
Ticket for all adaptions & fixes related to merging new Dataverse Version v5.12 and current mpdl-develop Version.

For the Release Notes of Dataverse v5.12, see: https://github.com/IQSS/dataverse/releases/tag/v5.12

**Comment by helkv** [comment]
Newest Dataverse v5.12.1 was merged into the current mpdl-develop version. Latest version is v5.12.1-mpdl-1.

For the Release Notes of Dataverse v5.12.1, see: https://github.com/IQSS/dataverse/releases/tag/v5.12.1

**Comment by helkv** [comment]
Testserver: qa-edmond2.mpdl.mpg.de
Browser: ff
Version: v5.12.1-mpdl-2 (https://github.com/MPDL/dataverse/commit/d23f4de0)
User: Admin
Result: OK
