### ISSUE TITLE
Create dataset: subject line of e-mail does not contain title of data set

### ISSUE THREAD

**Issue by hofmannc** [MPDL/dataverse#49]
Server: https://qa-edmond2.mpdl.mpg.de
Testdate: 08.11.2022
Browser: ff
Version: Dataverse v. 5.12.1
User: Admin
Action: create data set -> receive e-mail
Observation: Title of data set is not included to e-mail subject heading:
![image](https://user-images.githubusercontent.com/14921701/200596196-a4d219a8-aebe-4726-9ff1-d7aa436d38c8.png)
Expected result: instead of [""], title is displayed

**Comment by helkv** [comment]
Testserver: qa-edmond2.mpdl.mpg.de
Browser: ff
Version: v5.12.1-mpdl-2 (https://github.com/MPDL/dataverse/commit/d23f4de0)
User: Admin
Result: OK
