### ISSUE TITLE
Upload and download (incl. big data)

### ISSUE THREAD

**Issue by haarli** [MPDL/dataverse#5]
Große Dateien (max. 5 TB)

r2d2 soll auch den Upload und Download großer Datenmengen (im Terabyte-Bereich) unterstützen. Dies kann nicht über das Web Interface gehen.

Es muss noch definiert werden, bis zu welcher Dateigroße der normale Upload funktioniert und ab wann eine andere Lösung benötigt wird.

Upload: Wenn eine Datei zu groß ist für den normalen Upload bekommt der Nutzer einen Hinweis, was er jetzt tun muss.
Download: Der Download einer großen Datei ist nur über das Web Interface möglich. Es kann sein, dass dies mehrere Tage dauert und das evtl. das Programm wärend des Vorgangs ungewollt abgebrochen wird.

**Comment by hofmannc** [comment]
Testserver: prod-edmond2.mpdl.mpg.de
Browser: ff
Version: 08.02.2022
User: Dataverse Admin

Actions:

open data file -> "Upload files" -> select

Observation: If I batch upload more than +- 17 files, files are not added to data set see  #22
