### ISSUE TITLE
OptimisticLockingError when publishing a dataset after changing licenses

### ISSUE THREAD

**Issue by haarli** [MPDL/dataverse#50]
- Create a new dataset with a file
- Change License/terms
- Directly publish the dtaset afterwards
- => Publish fails, Dataset is locked

see IQSS/#9183

**Comment by helkv** [comment]
Testserver: qa-edmond2.mpdl.mpg.de
Browser: ff
Version: v5.12.1-mpdl-2 (https://github.com/MPDL/dataverse/commit/d23f4de0)
User: Admin
Result: OK
