### ISSUE TITLE
Hide Widgets Tab

### ISSUE THREAD

**Issue by haarli** [MPDL/dataverse#51]
The internal widget system (https://guides.dataverse.org/en/latest/user/dataset-management.html?highlight=widget#widgets) cannot be used in Edmond, as security measures prevent external iframes.
Therefore, the widgets tab on Dataset -> Edit -> Thumbnail&Widgets (Dataset must be published) should be hidden.

**Comment by haarli** [comment]
Fixed in https://github.com/MPDL/edmond-static-sites/commit/51f9e4c5b0dab7537451db74943bae8273179cf0

**Comment by hofmannc** [comment]
Server: qa-edmond2
Testdate: 28.03.2023
Browser: ff
Version: Dataverse v. 5.13
User: Admin

Test result: NOK

Action:
Publish data set -> "edit data set" -> "thumbnail and Widgets" -> 

Observation: widget tab is still available

Expected result: tab is hidden and Dropdown menue item is labeled " Thumbnails"

**Comment by haarli** [comment]
As this fix was independent of the release, but part of the static sites, it was not visibile on the QA server yet. 
There's a new version of the static sites on QA now, so it should work. Sorry for the confusion.

**Comment by hofmannc** [comment]
Re-tested -> ok
