### ISSUE TITLE
Preview for xhtml files

### ISSUE THREAD

**Issue by yvgrossmann** [MPDL/dataverse#67]
Currently there is no preview for xhtml files available.

One of our users communicated that this format is comparatively often used by them in their research data. It would therefore be interesting to be able to offer a preview for this.

Perhaps it is only a small extension, as there should be many similarities to html files.

Example of a forthcoming xhtml file:  https://edmond.mpdl.mpg.de/api/access/datafile/211447

**Comment by yvgrossmann** [comment]
Think about using the <description> fields to go on enhanced metadata transfer, as discussed on the Dataverse Community Meeting

**Comment by haarli** [comment]
HTML Previewer is now activated for XHTML files.
However, as within the the standard HTML files, some browsers might block certain html/xhtml files due to security restrictions.

**Comment by helkv** [comment]
Server: qa-edmond2 / qa.edmond.mpdl.mpg.de
Testdate: 02.10.2023
Browser: ff
Version: v5.14-mpdl-2 (b7c659383aaa1f687a858666a36d25dca24114d2)
User: User (helkv)
Result: OK

**Comment by hofmannc** [comment]
Server: qa-edmond2 / qa.edmond.mpdl.mpg.de
Testdate: 12.10.2023
Browser: ff
Version: v5.14-mpdl-2 
User: User 
Result: OK
