### ISSUE TITLE
Frontend / User Interface customizations

### ISSUE THREAD

**Issue by haarli** [MPDL/dataverse#7]
Inspiration might be the MPG Corporate Design:

https://max.mpg.de/Service/Mediathek/Pages/Corporate-Design.aspx
https://max.mpg.de/Service/Mediathek/corporate_design_downloads/Web-Styleguide/MPG-Web-Styleguide-2020-Version-1-0.pdf
https://max.mpg.de/Service/Mediathek/Pages/download-bereich.aspx

But this has to be discussed

**Comment by hofmannc** [comment]
Testserver: prod-edmond2.mpdl.mpg.de
Browser: ff
Version: 14.02.2022
User: Admin

Actions: checked UI


Observation: -> ok
