### ISSUE TITLE
Merge issues in v6.4

### ISSUE THREAD

**Issue by haarli** [MPDL/dataverse#79]
Datacite Export:
- ROR missing
- ORCID missing
- Multiple affiliations are missing

Labels: 
- ORCID watermark missing
- Organization Name 1 description differs from Organization Name 2 description

**Comment by helkv** [comment]
For changes/fixes of the Metadata Labels (ORCID watermark & Organization Name) see: https://github.com/MPDL/dataverse/issues/80

**Comment by helkv** [comment]
Server: qa.edmond.mpdl.mpg.de
Testdate: 07.11.2024
Browser: ff
Version: v6.4-mpdl-1 (https://github.com/MPDL/dataverse/commit/ae6c41e70949317e17ad02200ae13fce3d862342)
User: User (helkv)
Result: OK
