### ISSUE TITLE
Change labels for edmond

### ISSUE THREAD

**Issue by haarli** [MPDL/dataverse#8]
t.b.d.
Changing default label bundle or creating completely new label bundle?

**Comment by helkv** [comment]
Testserver: prod-edmond2.mpdl.mpg.de
Browser: ff
Version: 16.02.2022
User: User

Labels are successfully updated ('Edmond' Label exists & 'Dataverse' Label was removed) in the main views :heavy_check_mark: 

In some specific views/functionalities the 'Dataverse' Label is still visible :warning: 
It should be discussed whether the following occurrences of the 'Dataverse' Label should be replaced:
1. Main page -> Contact -> "Email Dataverse Contact"
2. Edit Dataset -> Permissions -> User/Groups -> "All the users and groups that have access to your dataverse."
3. Edit Dataset -> Permissions -> Roles -> "All the roles set up in your dataverse, that you can assign to users and groups." & "Admin - A person who has all permissions for dataverses, datasets, and files." & "Member - A person who can view both unpublished dataverses and datasets."
4. Dataset -> Terms Tab -> Terms of use -> "Our Community Norms as well as good scientific practices expect that proper credit is given via citation. Please use the data citation above, generated by the Dataverse."
5. User -> My Data -> "Here are all the dataverses, datasets, and files you have access to. You can filter through them by publication status and roles." & "Dataverses" (Filter option)
6. Dataset -> Share -> "Share Dataverse" & "Share this dataverse on your favorite social media networks."
