### ISSUE TITLE
Update of the Metadata Configuration Files: citation.properties & citation.tsv

### ISSUE THREAD

**Issue by helkv** [MPDL/dataverse#80]
The Edmond Metadata Configuration differs from original Dataverse Metadata Configuration due to specific requirements (see: https://github.com/MPDL/dataverse/issues/3). Also there is a constant change/update of the Dataverse Metadata Configuration by IQSS.

Update the Edmond Metadata Configuration (citation.properties & citation.tsv), to reduce the differences between the Edmond files and the original Dataverse files. At the same time Edmond specific changes of the Metadata should remain.

**Comment by helkv** [comment]
List of changes relevant for the Edmond Metadata:

| datasetfieldtype | Old value | New value |
| --- | --- | --- |
| title (description) | Full title by which the dataset is known. | The main title of the Dataset |
| datasetContact (description) | The contact(s) for this Dataset. | The entity, e.g. a person or organization, that users of the Dataset can contact with questions |
| topicClassification (description) | The classification field indicates the broad important topic(s) and subjects that the data cover. Library of Congress subject terms may be used here. | Indicates a broad, important topic or subject that the Dataset covers and information about any controlled vocabulary used |
| topicClassValue (description) | Topic or Subject term that is relevant to this Dataset. | A topic or subject term |
| topicClassVocab (description) | Provided for specification of the controlled vocabulary in use, e.g., LCSH, MeSH, etc. | The controlled vocabulary used for the keyword term (e.g. LCSH, MeSH) |
| topicClassVocabURI (description) | Specifies the URL location for the full controlled vocabulary.	Enter full URL, starting with http:// | The URL where one can access information about the term's controlled vocabulary |
| topicClassVocab (title) | Vocabulary | Controlled Vocabulary Name |
| topicClassVocabURI (title) | Vocabulary URL | Controlled Vocabulary URL |
| topicClassVocabURI (watermark) | Enter full URL, starting with http:// | https:// |
| language (description) | Language of the Dataset | A language that the Dataset's files is written in |
| grantNumber (title) | Grant Information | Funding Information |
| grantNumberAgency (title) | Grant Agency | Agency |
| grantNumberValue (title) | Grant Number | Identifier |
| grantNumber (description) | Grant Information | Information about the Dataset's financial support |
| grantNumberAgency (description) | Grant Agency | The agency that provided financial support for the Dataset |
| grantNumberValue (description) | The grant or contract number of the project that  sponsored the effort. | The grant identifier or contract identifier of the agency that provided financial support for the Dataset |
| grantNumberAgency (watermark) | - | Organization XYZ |
| softwareName (description) | Name of software used to generate the Dataset. | The name of software used to generate the Dataset |
| softwareVersion (description) | Version of the software used to generate the Dataset. | The version of the software used to generate the Dataset, e.g. 4.1 |
| publicationURL (watermark) | - | https:// |
| relatedDatasets (description) | Any Datasets that are related to this Dataset, such as previous research on this subject. | Information, such as a persistent ID or citation, about a related dataset, such as previous research on the Dataset's subject |

**Comment by hofmannc** [comment]
Server: qa-edmond2
Testdate: 06.11.2024
Browser: ff - windows
Version: Dataverse v. 6.4

Result: ok
