### ISSUE TITLE
Remove "Replication data for" button

### ISSUE THREAD

**Issue by haarli** [MPDL/dataverse#9]
When creating a new dataset, a button "Add Replication Data for" is displayed.

![grafik](https://user-images.githubusercontent.com/5524896/130934609-642ab14d-1273-442d-8139-1fc1b7564890.png)

This button should be hidden.

**Comment by helkv** [comment]
Testserver: prod-edmond2.mpdl.mpg.de
Browser: ff
Version: 15.02.2022
User: User

Actions:
- Create Dataset: Add Data -> New Dataset -> No button "Replication Data for" visible :heavy_check_mark: 
- Edit Dataset: Open Dataset -> Edit Dataset -> Metadata -> No button "Replication Data for" visible :heavy_check_mark: 

Observation:
All requirements implemented :heavy_check_mark:
